SUPABASE_URL= "https://fkhzeaxslijeyiyyvjkr.supabase.co"

SUPABASE_KEY="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZraHplYXhzbGlqZXlpeXl2amtyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjQ2ODAxNDIsImV4cCI6MjA4MDI1NjE0Mn0.FukZXzwxoZJmQ9-8V9rn_x1P__GBaTbrXaOkzChOxhY"
